spring.application.name=msnofity
server.port=8084

# ==========================================
# Configuración de RabbitMQ
# ==========================================
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# ==========================================
# Acks Manuales y Prefetch
# ==========================================
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=10
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# ==========================================
# Queues
# ==========================================
app.rabbitmq.queue.email=q.cmd.email
app.rabbitmq.queue.housekeeping=q.cmd.housekeeping
app.rabbitmq.queue.voucher=q.cmd.voucher

# ==========================================
# Servicio de Email
# ==========================================
resend.api-key=${RESEND_API_KEY:}
resend.from-email=${RESEND_FROM_EMAIL:onboarding@resend.dev}