spring.application.name=msnofity
server.port=8084
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.listener.simple.default-requeue-rejected=false

app.rabbitmq.queue.email=q.cmd.email
app.rabbitmq.queue.email-dlq=q.cmd.email.dlq
app.rabbitmq.queue.housekeeping=q.cmd.housekeeping
app.rabbitmq.queue.housekeeping-dlq=q.cmd.housekeeping.dlq
app.rabbitmq.queue.voucher=q.cmd.voucher
app.rabbitmq.queue.voucher-dlq=q.cmd.voucher.dlq

resend.api-key=${RESEND_API_KEY:}
resend.from-email=${RESEND_FROM_EMAIL:onboarding@resend.dev}