-- =====================================================================
-- ms-catalog | Seed data for UNITS
-- Idempotent: each row is only inserted if a unit with the same NAME
-- does not exist yet, so it is safe to run on every deployment.
-- UNIT_ID is generated by the DB (GenerationType.IDENTITY).
-- Prices are per night in CLP.
-- =====================================================================

-- ---------- HABITACION ----------
INSERT INTO UNITS (NAME, DESCRIPTION, ADDRESS, TYPE, CITY, AVAILABILITY, ROOMS, BATHROOMS, PRICE_PER_NIGHT, MAX_OCCUPANCY)
SELECT 'Habitación Cordillera', 'Habitación luminosa con vista a la cordillera de los Andes, cama king y escritorio.', 'Av. Providencia 1234', 'HABITACION', 'Santiago', TRUE, 1, 1, 45000.00, 2
WHERE NOT EXISTS (SELECT 1 FROM UNITS WHERE NAME = 'Habitación Cordillera');

INSERT INTO UNITS (NAME, DESCRIPTION, ADDRESS, TYPE, CITY, AVAILABILITY, ROOMS, BATHROOMS, PRICE_PER_NIGHT, MAX_OCCUPANCY)
SELECT 'Habitación Barrio Italia', 'Habitación acogedora a pasos de cafés y tiendas de diseño en Barrio Italia.', 'Av. Italia 1450', 'HABITACION', 'Santiago', TRUE, 1, 1, 38000.00, 2
WHERE NOT EXISTS (SELECT 1 FROM UNITS WHERE NAME = 'Habitación Barrio Italia');

INSERT INTO UNITS (NAME, DESCRIPTION, ADDRESS, TYPE, CITY, AVAILABILITY, ROOMS, BATHROOMS, PRICE_PER_NIGHT, MAX_OCCUPANCY)
SELECT 'Habitación Cerro Alegre', 'Habitación con balcón y vista a la bahía en el histórico Cerro Alegre.', 'Pasaje Gálvez 210', 'HABITACION', 'Valparaíso', FALSE, 1, 1, 42000.00, 2
WHERE NOT EXISTS (SELECT 1 FROM UNITS WHERE NAME = 'Habitación Cerro Alegre');

-- ---------- SUITE ----------
INSERT INTO UNITS (NAME, DESCRIPTION, ADDRESS, TYPE, CITY, AVAILABILITY, ROOMS, BATHROOMS, PRICE_PER_NIGHT, MAX_OCCUPANCY)
SELECT 'Suite Presidencial Andes', 'Suite de lujo con sala de estar, jacuzzi privado y terraza panorámica.', 'Av. Apoquindo 4500', 'SUITE', 'Santiago', TRUE, 2, 2, 180000.00, 4
WHERE NOT EXISTS (SELECT 1 FROM UNITS WHERE NAME = 'Suite Presidencial Andes');

INSERT INTO UNITS (NAME, DESCRIPTION, ADDRESS, TYPE, CITY, AVAILABILITY, ROOMS, BATHROOMS, PRICE_PER_NIGHT, MAX_OCCUPANCY)
SELECT 'Suite Ejecutiva Las Condes', 'Suite pensada para viajes de negocios: escritorio amplio, sala de reuniones y desayuno incluido.', 'Av. El Bosque Norte 500', 'SUITE', 'Santiago', TRUE, 1, 1, 95000.00, 2
WHERE NOT EXISTS (SELECT 1 FROM UNITS WHERE NAME = 'Suite Ejecutiva Las Condes');

INSERT INTO UNITS (NAME, DESCRIPTION, ADDRESS, TYPE, CITY, AVAILABILITY, ROOMS, BATHROOMS, PRICE_PER_NIGHT, MAX_OCCUPANCY)
SELECT 'Suite Vista al Mar', 'Suite frente al océano con tina de hidromasaje y terraza privada.', 'Av. San Martín 600', 'SUITE', 'Viña del Mar', TRUE, 2, 1, 150000.00, 3
WHERE NOT EXISTS (SELECT 1 FROM UNITS WHERE NAME = 'Suite Vista al Mar');

-- ---------- APARTAMENTO ----------
INSERT INTO UNITS (NAME, DESCRIPTION, ADDRESS, TYPE, CITY, AVAILABILITY, ROOMS, BATHROOMS, PRICE_PER_NIGHT, MAX_OCCUPANCY)
SELECT 'Apartamento Bellas Artes', 'Departamento completamente equipado frente al Parque Forestal, ideal para estadías largas.', 'José Miguel de la Barra 480', 'APARTAMENTO', 'Santiago', TRUE, 2, 1, 70000.00, 4
WHERE NOT EXISTS (SELECT 1 FROM UNITS WHERE NAME = 'Apartamento Bellas Artes');

INSERT INTO UNITS (NAME, DESCRIPTION, ADDRESS, TYPE, CITY, AVAILABILITY, ROOMS, BATHROOMS, PRICE_PER_NIGHT, MAX_OCCUPANCY)
SELECT 'Apartamento Costanera', 'Departamento moderno con cocina completa, gimnasio y piscina en el edificio.', 'Av. Andrés Bello 2425', 'APARTAMENTO', 'Santiago', TRUE, 3, 2, 110000.00, 6
WHERE NOT EXISTS (SELECT 1 FROM UNITS WHERE NAME = 'Apartamento Costanera');

INSERT INTO UNITS (NAME, DESCRIPTION, ADDRESS, TYPE, CITY, AVAILABILITY, ROOMS, BATHROOMS, PRICE_PER_NIGHT, MAX_OCCUPANCY)
SELECT 'Apartamento Playa Reñaca', 'Departamento a una cuadra de la playa, con balcón y estacionamiento.', 'Av. Borgoño 14500', 'APARTAMENTO', 'Viña del Mar', FALSE, 2, 1, 85000.00, 5
WHERE NOT EXISTS (SELECT 1 FROM UNITS WHERE NAME = 'Apartamento Playa Reñaca');

-- ---------- CABANA ----------
INSERT INTO UNITS (NAME, DESCRIPTION, ADDRESS, TYPE, CITY, AVAILABILITY, ROOMS, BATHROOMS, PRICE_PER_NIGHT, MAX_OCCUPANCY)
SELECT 'Cabaña Lago Villarrica', 'Cabaña de madera con vista al lago y volcán, tinaja de leña y quincho.', 'Camino Pucón-Villarrica Km 8', 'CABANA', 'Pucón', TRUE, 3, 2, 120000.00, 6
WHERE NOT EXISTS (SELECT 1 FROM UNITS WHERE NAME = 'Cabaña Lago Villarrica');

INSERT INTO UNITS (NAME, DESCRIPTION, ADDRESS, TYPE, CITY, AVAILABILITY, ROOMS, BATHROOMS, PRICE_PER_NIGHT, MAX_OCCUPANCY)
SELECT 'Cabaña Valle Nevado', 'Cabaña de montaña con chimenea, a minutos de las pistas de ski.', 'Camino a Farellones Km 12', 'CABANA', 'Lo Barnechea', TRUE, 2, 1, 135000.00, 4
WHERE NOT EXISTS (SELECT 1 FROM UNITS WHERE NAME = 'Cabaña Valle Nevado');

INSERT INTO UNITS (NAME, DESCRIPTION, ADDRESS, TYPE, CITY, AVAILABILITY, ROOMS, BATHROOMS, PRICE_PER_NIGHT, MAX_OCCUPANCY)
SELECT 'Cabaña Cajón del Maipo', 'Cabaña rodeada de naturaleza junto al río, perfecta para trekking y rafting.', 'Camino al Volcán 18000', 'CABANA', 'San José de Maipo', TRUE, 2, 1, 80000.00, 5
WHERE NOT EXISTS (SELECT 1 FROM UNITS WHERE NAME = 'Cabaña Cajón del Maipo');
