spring.application.name=msnofity
server.port=8084
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
app.rabbitmq.queue.email=q.cmd.email
app.rabbitmq.queue.housekeeping=q.cmd.housekeeping
app.rabbitmq.queue.voucher=q.cmd.voucher
resend.api-key=${RESEND_API_KEY:}
resend.from-email=${RESEND_FROM_EMAIL:onboarding@resend.dev}
