# ==========================================
# Configuración General del Microservicio
# ==========================================
spring.application.name=backend
server.port=8081

# ==========================================
# Azure AD (Spring Cloud Azure)
# ==========================================
spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.credential.client-id=ed8a85ef-f2d4-48c5-a17e-b69abfc4694e
spring.cloud.azure.active-directory.app-id-uri=api://ed8a85ef-f2d4-48c5-a17e-b69abfc4694e
# Reemplaza con el Tenant ID de tu App Registration en Azure AD
spring.cloud.azure.active-directory.profile.tenant-id=934f23a0-098f-4b94-81be-bc5360fd4eb4

# ==========================================
# Base de Datos Oracle
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5433/andesstay_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# Mensajería Asíncrona (RabbitMQ)
# ==========================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ==========================================
# Event Streaming (Kafka)
# ==========================================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer




# docker compose up -d
# ./mvnw spring-boot:run
# npm run dev 



# Usuario: Zatoo@domnerus1.onmicrosoft.com: Contraseña: santicapi123#
# Usuario: 