# ==========================================
# Configuración General del Microservicio
# ==========================================
spring.application.name=backend
server.port=8081

# ==========================================
# Azure AD (Spring Cloud Azure)
# ==========================================
spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.credential.client-id=5b6ffac2-680a-49ee-b8eb-12609107e903
spring.cloud.azure.active-directory.app-id-uri=api://5b6ffac2-680a-49ee-b8eb-12609107e903
# Reemplaza con el Tenant ID de tu App Registration en Azure AD
spring.cloud.azure.active-directory.profile.tenant-id=c46750c7-b258-426e-9333-5640bb4ecc6e

# ==========================================
# Base de Datos Oracle
# ==========================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=ANDESSTAY_USER
spring.datasource.password=andesstay_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# ==========================================
# Mensajería Asíncrona (RabbitMQ)
# ==========================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ==========================================
# Event Streaming (Kafka)
# ==========================================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ./mvnw spring-boot:run
# npm run dev 



# Usuario: Zatoo@domnerus1.onmicrosoft.com: Contraseña: santicapi123#
# Usuario: 