spring.application.name=backend

server.port=8081

# Habilitar integración con Azure AD
spring.cloud.azure.active-directory.enabled=true

# Client ID del registro del API en Entra ID
spring.cloud.azure.active-directory.credential.client-id=ed8a85ef-f2d4-48c5-a17e-b69abfc4694e

# Application ID URI configurado en "Exponer una API"
spring.cloud.azure.active-directory.app-id-uri=api://ed8a85ef-f2d4-48c5-a17e-b69abfc4694e


