CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id BIGINT NOT NULL,
    guest_id VARCHAR(255) NOT NULL,
    guest_email VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT chk_reservations_dates
        CHECK (end_date > start_date),

    CONSTRAINT chk_reservations_total_amount
        CHECK (total_amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_reservations_unit_id
    ON reservations (unit_id);

CREATE INDEX IF NOT EXISTS idx_reservations_status
    ON reservations (status);

CREATE INDEX IF NOT EXISTS idx_reservations_start_date
    ON reservations (start_date);

CREATE INDEX IF NOT EXISTS idx_reservations_created_at
    ON reservations (created_at DESC, id DESC);